// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qobcsrayeohmysljahym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvYmNzcmF5ZW9obXlzbGphaHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDkxOTUsImV4cCI6MjA3MzI4NTE5NX0.KvEfzV3MXE87MQ_z3e4dyYudU0IYXyGV56c59Cc3fLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});